server:
  port: 8084

spring:
  main:
    allow-bean-definition-overriding: true
#  mvc:
#    # 静态资源路径
#    static-path-pattern: /**
#    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#    view:
#      prefix: classpath:static/templates/
#      suffix: .html


manual:
  fault:
    enable: false


feign:
  custom-routing:
    enabled: true
    services:
      pec-service:
        - http://172.17.6.121:4118
        - http://172.17.6.173:4118
      iot-node-serviefc:
        - http://172.17.6.121:4118
        - http://172.17.6.173:4118
logging:
  level:
    com:
      cet:
        futureblue:
          fusionsenhighfacade:
            core:
              config: debug
              service:
                impl: debug
              loadbalancer: debug