server:
  port: 8084

eureka:
  instance:
    hostname: 172.17.6.121
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/
    registry-fetch-interval-seconds: 5

spring:
  main:
    allow-bean-definition-overriding: true
#  mvc:
#    # 静态资源路径
#    static-path-pattern: /**
#    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#    view:
#      prefix: classpath:static/templates/
#      suffix: .html

manual:
  fault:
    enable: false

feign:
  custom-routing:
    enabled: true
    services:
      pec-service:
        - http://172.17.6.121:4118
        - http://172.17.6.173:4118
      config-server:
        - http://172.17.6.121:4119
        - http://172.17.6.173:4119

logging:
  level:
    com:
      cet:
        futureblue:
          fusionsenhighfacade:
            core:
              config: debug
              service:
                impl: debug
              loadbalancer: debug